### ISSUE TITLE
NuWeather: geolookup errors

### ISSUE THREAD

**Issue by uhlhosting** [jlu5/SupyPlugins#86]
I received this no matter what backend I used for geolookup.

```
ERROR 2019-07-12T21:23:57 supybot Uncaught exception in ['geolookup'].
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supybot/callbacks.py", line 1319, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/supybot/utils/python.py", line 90, in g
    f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/supybot/callbacks.py", line 1285, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/supybot/commands.py", line 1104, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/vcm/sentinel/plugins/NuWeather/plugin.py", line 510, in geolookup
    available_geocode_backends = self._get_available_geocode_backends()
AttributeError: 'NuWeather' object has no attribute '_get_available_geocode_backends'
ERROR 2019-07-12T21:23:57 supybot Exception id: 0xa281f
```

**Comment by jlu5** [comment]
https://github.com/jlu5/SupyPlugins/commit/884ca91f668442a6ce6e2fdf1552e19985ea9b76
This is already fixed in Git, you just need to update your copy of the plugin

**Comment by uhlhosting** [comment]
@jlu5 is a way to do this from the bot? Or I need to run manually?

**Comment by uhlhosting** [comment]
Solved just had to remove the two lines. Thanks!

**Comment by jlu5** [comment]
You can upgrade from the bot by running `install` from PluginDownloader again - it should replace what you had before. If you're checking out from git, do `git pull`.
